const types=[
 {id:'free-line',name:'自由線',sub:'自由配置・回転',color:'#d32f2f',w:7,h:0.5,count:1},
 {id:'free-frame',name:'自由枠',sub:'自由配置・伸縮',color:'#d32f2f',w:7,h:3.5,count:1},
 {id:'stairs-code',name:'管理用階段',sub:'5m × 3m',color:'#c65f3e',w:5,h:3,count:1},
 {id:'stairs-access',name:'利用者階段',sub:'7m × 3.5m',color:'#d58445',w:7,h:3.5,count:1},
 {id:'ev-large',name:'EV（管理用）',sub:'5m × 2.5m',color:'#6b536f',w:5,h:2.5,count:1},
 {id:'ev-small',name:'EV（利用者用）',sub:'2m × 2m',color:'#856b8b',w:2,h:2,count:1},
 {id:'corridor-wide',name:'廊下（2.5m幅）',sub:'自由伸縮',color:'#9a8e77',w:7,h:2.5,count:1},
 {id:'corridor-standard',name:'廊下（2m幅）',sub:'自由伸縮',color:'#b0a48e',w:7,h:2,count:1},
 {id:'toilet',name:'共用トイレ',sub:'最小1単位',color:'#345d88',w:7,h:3.5,unit:true,count:1},
 {id:'linen',name:'リネン室',sub:'3.5m × 3m',color:'#7a8f99',w:3.5,h:3,unit:true,count:1},
 {id:'air-cond',name:'空調室',sub:'3m × 2m・約6㎡',color:'#8f9592',w:3,h:2,unit:true,count:1},
 {id:'room-single',name:'シングル',sub:'1人用・18㎡目安',color:'#f7cdd8',w:2.5,h:7,unit:true,count:1},
 {id:'room-semidouble',name:'セミダブル',sub:'1～2人用・20㎡目安',color:'#f2b8c8',w:3,h:7,unit:true,count:1},
 {id:'room-double',name:'ダブル',sub:'2人用・24㎡目安',color:'#eca3b8',w:3.5,h:7,unit:true,count:1},
 {id:'room-twin',name:'ツイン',sub:'2人用・26㎡目安',color:'#e58ea8',w:4,h:7,unit:true,count:1},
 {id:'room-triple',name:'トリプル',sub:'3人用・32㎡目安',color:'#e2799b',w:4.5,h:7,unit:true,count:1},
 {id:'room-deluxe-twin',name:'デラックスツイン',sub:'2人用・34㎡目安',color:'#d9678c',w:5,h:7,unit:true,count:1},
 {id:'room-accessible',name:'身障者・車いす対応',sub:'1～2人用・32㎡目安',color:'#4a90a4',w:5,h:7,unit:true,count:1},
 {id:'room-family',name:'ファミリー',sub:'3～4人用・40㎡目安',color:'#cf5580',w:5.5,h:7,unit:true,count:1},
 {id:'room-family-large',name:'ファミリー大',sub:'4～5人用・48㎡目安',color:'#c04572',w:7,h:7,unit:true,count:1},
 {id:'room-junior-suite',name:'ジュニアスイート',sub:'2人用・45㎡目安',color:'#b23a66',w:6.5,h:7,unit:true,count:1},
 {id:'room-suite',name:'スイート',sub:'2～4人用・65㎡目安',color:'#9c2f58',w:9.5,h:7,unit:true,count:1}
];
const floorDefs=[['standard','基準階']]; let selectedType='room-single', selectedPiece=null, history=[];
let state=JSON.parse(localStorage.getItem('esquisse_state')||'null')||{version:4,rows:4,cols:6,pieces:[]};
if(state.version!==4){state={version:4,rows:state.rows||4,cols:state.cols||6,pieces:[]};localStorage.setItem('esquisse_state',JSON.stringify(state))}
state.rowSpan=state.rowSpan||6;state.colSpan=state.colSpan||7;state.notch=state.notch||null;state.pieces=state.pieces.filter(p=>types.some(t=>t.id===p.type)&&floorDefs.some(([f])=>f===p.floor));
const $=s=>document.querySelector(s), rooms=$('#rooms'), floors=$('#floors');
const typeSize=t=>t.sw?{w:t.sw*state.colSpan,h:t.sh*state.rowSpan}:{w:t.w,h:t.h};
function snap(){history.push(JSON.stringify(state));if(history.length>30)history.shift()}
function persist(){localStorage.setItem('esquisse_state',JSON.stringify(state))}
const roomSymbols={'room-single':'S','room-semidouble':'SD','room-double':'D','room-twin':'T','room-triple':'Tr','room-deluxe-twin':'DT','room-accessible':'♿','room-family':'F','room-family-large':'F+','room-junior-suite':'JS','room-suite':'ST',linen:'リ','air-cond':'空'};
const alwaysVisibleTypeIds=['stairs-code','stairs-access','corridor-wide','corridor-standard','free-line','free-frame'];
function renderRooms(){rooms.innerHTML=types.filter(t=>t.count>0||alwaysVisibleTypeIds.includes(t.id)).map(t=>{const d=typeSize(t),corridor=t.id.startsWith('corridor'),line=t.id==='free-line',symbol=line?'／':t.id.startsWith('stairs')?'階':t.id.startsWith('ev')?'EV':corridor?'廊':roomSymbols[t.id]||Math.round(d.w*d.h/24.5),detail=`${t.sub}${corridor||line?'':`・${d.w}×${d.h}m`}`,areaMatch=t.sub.match(/([\d.]+)㎡/),area=areaMatch?`<span class="room-area">${areaMatch[1]}㎡</span>`:'';return `<div class="room-row ${selectedType===t.id?'active':''}" data-id="${t.id}" title="${t.name}（${detail}）"><span class="swatch" style="background:${t.color}">${symbol}</span><span class="room-name">${t.name}</span>${area}<input aria-label="${t.name}の個数" data-count="${t.id}" type="number" min="0" max="30" value="${t.count}"></div>`}).join('')}
function columnMarkers(totalW,totalH){const n=notchRect();let html='';for(let i=0;i<=state.cols;i++)for(let j=0;j<=state.rows;j++){const x=i*state.colSpan,y=j*state.rowSpan;if(n&&x>=n.x&&x<=n.x+n.w&&y>=n.y&&y<=n.y+n.h)continue;html+=`<i class="column-marker" style="left:${x/totalW*100}%;top:${y/totalH*100}%"></i>`}return html}
function renderFloors(){const totalW=state.cols*state.colSpan,totalH=state.rows*state.rowSpan,n=notchRect(),notch=n?`<i class="site-notch" style="left:${n.x/totalW*100}%;top:${n.y/totalH*100}%;width:${n.w/totalW*100}%;height:${n.h/totalH*100}%"><span>計画対象外</span></i>`:'',notchLabel=n?`（${cornerNames[state.notch.corner]}${n.w}×${n.h}mを除くL型）`:'';floors.innerHTML=floorDefs.map(([id,name])=>`<section class="floor" data-floor="${id}"><div class="floor-title"><b>${name}</b><span>${totalW}m × ${totalH}m${notchLabel}</span></div><div class="grid-wrap"><div class="row-dims" style="grid-template-rows:repeat(${state.rows},1fr)">${Array(state.rows).fill(`<span>${state.rowSpan}</span>`).join('')}</div><div class="grid" data-grid="${id}" style="aspect-ratio:${totalW}/${totalH};grid-template-columns:repeat(${state.cols},1fr);grid-template-rows:repeat(${state.rows},1fr);background-size:${100/state.cols}% ${100/state.rows}%">${columnMarkers(totalW,totalH)}${notch}</div><div class="col-dims" style="grid-template-columns:repeat(${state.cols},1fr)">${Array(state.cols).fill(`<span>${state.colSpan}</span>`).join('')}</div></div></section>`).join(''); state.pieces.forEach(drawPiece); bindGrid(); updateSummary()}
function drawPiece(p){const g=document.querySelector(`[data-grid="${p.floor}"]`);if(!g)return;const t=types.find(x=>x.id===p.type);if(!t)return;const e=document.createElement('div'),totalW=state.cols*state.colSpan,totalH=state.rows*state.rowSpan,showHandle=p.id===selectedPiece,corridor=p.type.startsWith('corridor'),measure=`${p.w}×${p.h}m・${p.w*p.h}㎡`;e.className='piece'+(p.id===selectedPiece?' selected':'');e.dataset.pid=p.id;e.style.cssText=`left:${p.x/totalW*100}%;top:${p.y/totalH*100}%;width:${p.w/totalW*100}%;height:${p.h/totalH*100}%;background:${t.color}`;e.innerHTML=`<span>${t.name}<small>${$('#areas').checked&&!corridor?`<br>${measure}`:''}</small></span>${showHandle?'<i class="resize-handle corner" title="ドラッグして縦横を変更"></i>':''}`;g.append(e)}
const drawPieceBase=drawPiece;
drawPiece=function(p){if(!isFreeLine(p.type))return drawPieceBase(p);const g=document.querySelector(`[data-grid="${p.floor}"]`),t=types.find(x=>x.id===p.type);if(!g||!t)return;const e=document.createElement('div'),totalW=state.cols*state.colSpan,totalH=state.rows*state.rowSpan,angle=((p.angle??0)%360+360)%360;e.className='piece drafting drafting-free-line'+(p.id===selectedPiece?' selected':'');e.dataset.pid=p.id;e.style.cssText=`left:${p.x/totalW*100}%;top:${p.y/totalH*100}%;width:${p.w/totalW*100}%;height:${p.h/totalH*100}%;--arrow-angle:${angle}deg`;e.innerHTML=`<span>自由線</span>${p.id===selectedPiece?'<i class="resize-handle corner" title="ドラッグして線を伸縮"></i>':''}`;g.append(e)};
const drawPieceFreeLineBase=drawPiece;
drawPiece=function(p){if(p.type!=='free-frame')return drawPieceFreeLineBase(p);const g=document.querySelector(`[data-grid="${p.floor}"]`);if(!g)return;const e=document.createElement('div'),totalW=state.cols*state.colSpan,totalH=state.rows*state.rowSpan;e.className='piece drafting drafting-free-frame'+(p.id===selectedPiece?' selected':'');e.dataset.pid=p.id;e.style.cssText=`left:${p.x/totalW*100}%;top:${p.y/totalH*100}%;width:${p.w/totalW*100}%;height:${p.h/totalH*100}%`;e.innerHTML=`<span>自由枠<small><br>${p.w}×${p.h}m</small></span>${p.id===selectedPiece?'<i class="resize-handle corner" title="ドラッグして縦横を変更"></i>':''}`;g.append(e)};
const isCoreType=id=>id.startsWith('stairs')||id.startsWith('ev');
const isFreeLine=id=>id==='free-line';
const isFreeFrame=id=>id==='free-frame';
const isDraftingType=id=>isFreeLine(id)||isFreeFrame(id);
const cornerNames={ne:'北東',nw:'北西',se:'南東',sw:'南西'};
function notchRect(){if(!state.notch)return null;const totalW=state.cols*state.colSpan,totalH=state.rows*state.rowSpan,n=state.notch,x=n.corner.includes('e')?totalW-n.w:0,y=n.corner.includes('s')?totalH-n.h:0;return{x,y,w:n.w,h:n.h}}
function overlapsNotch(x,y,w,h){const n=notchRect();return!!n&&x<n.x+n.w&&x+w>n.x&&y<n.y+n.h&&y+h>n.y}
const linked=p=>p.groupId?state.pieces.filter(x=>x.groupId===p.groupId):[p];
function snapEdge(value,size,span,total){const candidates=[];for(let line=0;line<=total+.001;line+=span){candidates.push(line,line-size)}const valid=candidates.filter(v=>v>=0&&v+size<=total+.001);return valid.reduce((best,v)=>Math.abs(v-value)<Math.abs(best-value)?v:best,valid[0]??0)}
function snapToGrid(x,y,w,h){const totalW=state.cols*state.colSpan,totalH=state.rows*state.rowSpan,half=n=>Math.round(n*2)/2;return{x:Math.max(0,Math.min(half(x),half(totalW-w))),y:Math.max(0,Math.min(half(y),half(totalH-h)))}}
function snapToNeighbors(floor,x,y,w,h,ignoreIds){const totalW=state.cols*state.colSpan,totalH=state.rows*state.rowSpan,threshold=1.2,minOverlap=1;let bestX=null,bestXd=threshold,bestY=null,bestYd=threshold;for(const p of state.pieces){if(p.floor!==floor||ignoreIds.includes(p.id)||isDraftingType(p.type)||isFreeLine(p.type))continue;const overlapY=Math.min(y+h,p.y+p.h)-Math.max(y,p.y);if(overlapY>=minOverlap){let d=Math.abs(x-(p.x+p.w));if(d<bestXd){bestXd=d;bestX=p.x+p.w}d=Math.abs((x+w)-p.x);if(d<bestXd){bestXd=d;bestX=p.x-w}}const overlapX=Math.min(x+w,p.x+p.w)-Math.max(x,p.x);if(overlapX>=minOverlap){let d=Math.abs(y-(p.y+p.h));if(d<bestYd){bestYd=d;bestY=p.y+p.h}d=Math.abs((y+h)-p.y);if(d<bestYd){bestYd=d;bestY=p.y-h}}}if(bestX!==null)x=Math.max(0,Math.min(bestX,totalW-w));if(bestY!==null)y=Math.max(0,Math.min(bestY,totalH-h));return{x,y}}
function canPlace(f,x,y,w,h,ignore=[],movingType=''){const ids=Array.isArray(ignore)?ignore:[ignore],totalW=state.cols*state.colSpan,totalH=state.rows*state.rowSpan;if(isFreeLine(movingType))return x>=-totalW&&y>=-totalH&&x+w<=totalW*2&&y+h<=totalH*2;return x>=0&&y>=0&&x+w<=totalW&&y+h<=totalH&&!overlapsNotch(x,y,w,h)&&!state.pieces.some(p=>p.floor===f&&!ids.includes(p.id)&&!isDraftingType(p.type)&&!isFreeLine(p.type)&&x<p.x+p.w&&x+w>p.x&&y<p.y+p.h&&y+h>p.y)}
function place(f,x,y){const t=types.find(v=>v.id===selectedType),d=typeSize(t),w=d.w,h=d.h,base=snapToGrid(x,y,w,h);let pos=base;if(!isDraftingType(t.id)){const snapped=snapToNeighbors(f,base.x,base.y,w,h,[]);if(canPlace(f,snapped.x,snapped.y,w,h,[],t.id))pos=snapped}x=pos.x;y=pos.y;if(!canPlace(f,x,y,w,h,[],t.id)){toast('ここには配置できません');return}snap();const created={id:crypto.randomUUID(),groupId:null,type:t.id,floor:f,x,y,w,h,rotated:false};state.pieces.push(created);selectedPiece=created.id;persist();renderFloors();renderSelection()}
const canPlaceBase=canPlace;
canPlace=function(f,x,y,w,h,ignore=[],movingType=''){if(isFreeFrame(movingType)){const totalW=state.cols*state.colSpan,totalH=state.rows*state.rowSpan;return x>=-totalW&&y>=-totalH&&x+w<=totalW*2&&y+h<=totalH*2}return canPlaceBase(f,x,y,w,h,ignore,movingType)};
const placeBase=place;
place=function(f,x,y){if(selectedType!=='free-line'&&selectedType!=='free-frame')return placeBase(f,x,y);const t=types.find(v=>v.id===selectedType),d=typeSize(t),totalW=state.cols*state.colSpan,totalH=state.rows*state.rowSpan;x=Math.max(-totalW,Math.min(Math.round(x*2)/2,totalW*2-d.w));y=Math.max(-totalH,Math.min(Math.round(y*2)/2,totalH*2-d.h));snap();const p={id:crypto.randomUUID(),groupId:null,type:t.id,floor:f,x,y,w:d.w,h:d.h,angle:0,rotated:false};state.pieces.push(p);selectedPiece=p.id;persist();renderFloors();renderSelection();toast(`${t.name}を配置しました`)};
function bindGrid(){document.querySelectorAll('.grid').forEach(g=>{
 g.onmousedown=e=>{
  if(e.button!==0)return;
  const rect=g.getBoundingClientRect(),snap05=n=>Math.floor(n*2)/2,x=snap05((e.clientX-rect.left)/rect.width*state.cols*state.colSpan),y=snap05((e.clientY-rect.top)/rect.height*state.rows*state.rowSpan),hit=e.target.closest('.piece'),isResize=!!e.target.closest('.resize-handle');
  if(!hit){place(g.dataset.grid,x,y);return}
  selectedPiece=hit.dataset.pid;renderFloors();renderSelection();
  const p=state.pieces.find(q=>q.id===selectedPiece),parts=linked(p),ids=parts.map(v=>v.id),startX=x,startY=y,origins=parts.map(v=>({p:v,x:v.x,y:v.y}));snap();
  if(isResize){const move=ev=>{const px=snap05((ev.clientX-rect.left)/rect.width*state.cols*state.colSpan),py=snap05((ev.clientY-rect.top)/rect.height*state.rows*state.rowSpan),nw=Math.max(.5,Math.round((px-p.x)*2)/2),nh=Math.max(.5,Math.round((py-p.y)*2)/2);if(parts.every(v=>canPlace(v.floor,v.x,v.y,nw,nh,ids,v.type))){parts.forEach(v=>{v.w=nw;v.h=nh});renderFloors();renderSelection()}};const up=()=>{persist();window.removeEventListener('mousemove',move);window.removeEventListener('mouseup',up)};window.addEventListener('mousemove',move);window.addEventListener('mouseup',up);return}
  const move=ev=>{const nx=snap05((ev.clientX-rect.left)/rect.width*state.cols*state.colSpan),ny=snap05((ev.clientY-rect.top)/rect.height*state.rows*state.rowSpan),dx=nx-startX,dy=ny-startY,targets=origins.map(v=>{if(isDraftingType(v.p.type))return{v,x:v.x+dx,y:v.y+dy};const pos=snapToGrid(v.x+dx,v.y+dy,v.p.w,v.p.h);return{v,x:pos.x,y:pos.y}});if(targets.every(t=>canPlace(t.v.p.floor,t.x,t.y,t.v.p.w,t.v.p.h,ids,t.v.p.type))){targets.forEach(t=>{t.v.p.x=t.x;t.v.p.y=t.y});renderFloors()}};
  const up=()=>{persist();window.removeEventListener('mousemove',move);window.removeEventListener('mouseup',up)};window.addEventListener('mousemove',move);window.addEventListener('mouseup',up)
 };
  g.oncontextmenu=e=>{e.preventDefault();const hit=e.target.closest('.piece'),rect=g.getBoundingClientRect(),x=Math.round((e.clientX-rect.left)/rect.width*state.cols*state.colSpan*2)/2,y=Math.round((e.clientY-rect.top)/rect.height*state.rows*state.rowSpan*2)/2;showContextMenu(e.clientX,e.clientY,hit?.dataset.pid||null,g.dataset.grid,x,y)}
})}
document.addEventListener('mousedown',e=>{const handle=e.target.closest('.drafting-free-line .resize-handle');if(!handle||e.button!==0)return;const pieceEl=handle.closest('.piece'),p=state.pieces.find(v=>v.id===pieceEl.dataset.pid),g=pieceEl.closest('.grid');if(!p||!g)return;e.preventDefault();e.stopImmediatePropagation();const rect=g.getBoundingClientRect(),totalW=state.cols*state.colSpan,totalH=state.rows*state.rowSpan,angle=(p.angle??0)*Math.PI/180,cos=Math.cos(angle),sin=Math.sin(angle),startClientX=e.clientX,startClientY=e.clientY,startW=p.w,startX=p.x,startY=p.y;snap();const move=ev=>{const dx=(ev.clientX-startClientX)/rect.width*totalW,dy=(ev.clientY-startClientY)/rect.height*totalH,newW=Math.max(.5,Math.round((startW+dx*cos+dy*sin)*2)/2),change=newW-startW,newX=startX+change*(cos-1)/2,newY=startY+change*sin/2;if(canPlace(p.floor,newX,newY,newW,p.h,p.id,p.type)){p.x=newX;p.y=newY;p.w=newW;renderFloors();renderSelection()}};const up=()=>{persist();window.removeEventListener('mousemove',move);window.removeEventListener('mouseup',up)};window.addEventListener('mousemove',move);window.addEventListener('mouseup',up)},true);
let copiedPiece=null;
function deletePiece(id){const p=state.pieces.find(v=>v.id===id);if(!p)return;snap();const ids=linked(p).map(v=>v.id);state.pieces=state.pieces.filter(v=>!ids.includes(v.id));selectedPiece=null;persist();renderFloors();renderSelection()}
function pastePiece(floor,x,y){if(!copiedPiece)return;const t=types.find(v=>v.id===copiedPiece.type);selectedType=copiedPiece.type;const base=snapToGrid(x,y,copiedPiece.w,copiedPiece.h);let pos=base;if(!isDraftingType(t.id)){const snapped=snapToNeighbors(floor,base.x,base.y,copiedPiece.w,copiedPiece.h,[]);if(canPlace(floor,snapped.x,snapped.y,copiedPiece.w,copiedPiece.h,[],t.id))pos=snapped}if(!canPlace(floor,pos.x,pos.y,copiedPiece.w,copiedPiece.h,[],t.id))return toast('ここには貼り付けできません');snap();const created={...copiedPiece,id:crypto.randomUUID(),groupId:null,floor,x:pos.x,y:pos.y};state.pieces.push(created);selectedPiece=created.id;persist();renderFloors();renderSelection();toast('貼り付けました')}
function showContextMenu(clientX,clientY,id,floor,x,y){const menu=$('#context-menu');menu.innerHTML=id?'<button data-action="copy">コピー</button><button data-action="delete">削除</button>':copiedPiece?'<button data-action="paste">貼り付け</button>':'<span>コピーした要素がありません</span>';menu.hidden=false;menu.style.left=clientX+'px';menu.style.top=clientY+'px';menu.onclick=e=>{const action=e.target.dataset.action;if(action==='copy'){const p=state.pieces.find(v=>v.id===id);copiedPiece=p?{...p,groupId:null}:null;toast('コピーしました')}if(action==='delete')deletePiece(id);if(action==='paste')pastePiece(floor,x,y);menu.hidden=true}}
document.addEventListener('mousedown',e=>{const m=$('#context-menu');if(!m.contains(e.target))m.hidden=true});
function renderSelection(){const p=state.pieces.find(x=>x.id===selectedPiece),box=$('#selection');if(!p){box.className='empty';box.textContent='要素を選択してください';return}const t=types.find(x=>x.id===p.type),parts=linked(p),ids=parts.map(v=>v.id),corridor=p.type.startsWith('corridor'),draft=isDraftingType(p.type),length=p.rotated?p.h:p.w,detail=p.type==='site-line'?`長さ ${Math.max(p.w,p.h)}m`:draft?`${p.w}m × ${p.h}m`:`${p.w}m × ${p.h}m・${p.w*p.h}㎡`;box.className='selection-card';box.innerHTML=`<b><span style="color:${t.color}">■</span> ${t.name}</b><span>${detail}</span>${corridor?`<label>廊下の長さ（m）<input id="corridor-length" type="number" min="2.5" step="0.5" value="${length}"></label><span class="resize-buttons"><button id="shorten">− 0.5m</button><button id="lengthen">＋ 0.5m</button></span>`:''}<button id="rotate">↻ 90°回転</button><button id="remove">選択した要素を削除</button>`;const resize=value=>{value=Math.max(2.5,Math.round(value*2)/2);const nw=p.rotated?p.w:value,nh=p.rotated?value:p.h;if(canPlace(p.floor,p.x,p.y,nw,nh,p.id,p.type)){snap();p.w=nw;p.h=nh;persist();renderFloors();renderSelection()}else toast('その長さには変更できません')};if(corridor){$('#corridor-length').onchange=e=>resize(+e.target.value);$('#shorten').onclick=()=>resize(length-.5);$('#lengthen').onclick=()=>resize(length+.5)}$('#rotate').onclick=()=>{if(parts.every(v=>canPlace(v.floor,v.x,v.y,v.h,v.w,ids,v.type))){snap();parts.forEach(v=>{[v.w,v.h]=[v.h,v.w];v.rotated=!v.rotated});persist();renderFloors();renderSelection()}else toast('回転する余白がありません')};$('#remove').onclick=()=>{snap();state.pieces=state.pieces.filter(x=>!ids.includes(x.id));selectedPiece=null;persist();renderFloors();renderSelection()}}
const renderSelectionRotatableBase=renderSelection;
renderSelection=function(){renderSelectionRotatableBase();const p=state.pieces.find(x=>x.id===selectedPiece);if(!p||!isFreeLine(p.type))return;const box=$('#selection'),angle=((p.angle??0)%360+360)%360,label=document.createElement('label');label.innerHTML=`線の角度（°）<input id="line-angle" type="range" min="0" max="359" step="1" value="${angle}"><input id="line-angle-number" type="number" min="0" max="359" step="1" value="${angle}">`;box.insertBefore(label,$('#rotate'));const setAngle=(value,refresh=true)=>{p.angle=((Math.round(value)%360)+360)%360;persist();renderFloors();if(refresh)renderSelection()};$('#line-angle').oninput=e=>{setAngle(+e.target.value,false);$('#line-angle-number').value=e.target.value};$('#line-angle-number').onchange=e=>setAngle(+e.target.value);$('#rotate').textContent='↻ 45°回転';$('#rotate').onclick=()=>{snap();setAngle(angle+45)}};
function updateSummary(){const keys=new Set(state.pieces.map(p=>p.groupId||p.id)),total=types.reduce((n,t)=>n+t.count,0);$('#summary').textContent=`配置 ${keys.size} / ${total} コマ`}
function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
rooms.onclick=e=>{if(e.target.matches('input'))return;const row=e.target.closest('.room-row');if(row){selectedType=row.dataset.id;renderRooms()}};rooms.onchange=e=>{const t=types.find(x=>x.id===e.target.dataset.count);if(t){t.count=+e.target.value;updateSummary()}};
$('#areas').onchange=renderFloors;
$('#undo').onclick=()=>{if(!history.length)return toast('戻せる操作がありません');state=JSON.parse(history.pop());persist();renderFloors();renderSelection()};$('#clear').onclick=()=>{if(confirm('配置した部屋をすべて消しますか？')){snap();state.pieces=[];selectedPiece=null;persist();renderFloors();renderSelection()}};
$('#all-clear').onclick=()=>{if(!confirm('配置・グリッドをすべて初期状態に戻しますか？'))return;state={version:4,rows:4,cols:6,rowSpan:6,colSpan:7,notch:null,pieces:[]};syncRoomCounts();history=[];copiedPiece=null;selectedPiece=null;selectedType='room-single';localStorage.removeItem('esquisse_state');persist();renderRooms();renderFloors();renderSelection();toast('すべて初期状態に戻しました')};
$('#reset').onclick=()=>{syncRoomCounts();renderRooms();updateSummary()};
$('#save').onclick=()=>{window.print();toast('印刷画面からPDF・画像として保存できます')};renderRooms();renderFloors();renderSelection();
