const learningChallenges=[
 {id:'hotel-business-single',title:'ビジネスホテル基準階（シングル中心）',level:'初級',brief:'シングルを中心に、セミダブル・身障者対応客室を組み合わせた効率的な二重廊下型の基準階を計画する。',grid:{rows:3,cols:6,rowSpan:6,colSpan:7},requirements:[
  {floor:'standard',type:'room-single',count:12,area:17.5,note:'1人用'},{floor:'standard',type:'room-semidouble',count:4,area:21,note:'1～2人用'},{floor:'standard',type:'room-accessible',count:2,area:35,note:'身障者・車いす対応'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-city-mix',title:'シティホテル基準階（標準客室ミックス）',level:'標準',brief:'ダブル・ツイン・トリプルを組み合わせ、二方向避難と客室動線を両立させる。',grid:{rows:3,cols:6,rowSpan:7,colSpan:6},requirements:[
  {floor:'standard',type:'room-double',count:6,area:24.5},{floor:'standard',type:'room-twin',count:8,area:28},{floor:'standard',type:'room-triple',count:2,area:31.5},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-resort-family',title:'リゾートホテル基準階（ファミリー中心）',level:'上級',brief:'ファミリー・ファミリー大・デラックスツインを中心に、大型客室の動線と避難経路を検討する。',grid:{rows:3,cols:7,rowSpan:7,colSpan:7},requirements:[
  {floor:'standard',type:'room-family',count:6,area:38.5},{floor:'standard',type:'room-family-large',count:4,area:49},{floor:'standard',type:'room-deluxe-twin',count:4,area:35},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-luxury-suite',title:'ラグジュアリーホテル基準階（スイート中心）',level:'上級',brief:'ジュニアスイート・スイートを中心とした高グレード客室階を計画する。',grid:{rows:3,cols:5,rowSpan:8,colSpan:7},requirements:[
  {floor:'standard',type:'room-junior-suite',count:4,area:45.5},{floor:'standard',type:'room-suite',count:2,area:66.5},{floor:'standard',type:'room-deluxe-twin',count:4,area:35},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-universal',title:'ユニバーサル対応強化型基準階',level:'標準',brief:'身障者・車いす対応客室を複数配置し、避難経路とアクセス動線を重点的に検討する。',grid:{rows:3,cols:5,rowSpan:7,colSpan:8},requirements:[
  {floor:'standard',type:'room-accessible',count:4,area:35},{floor:'standard',type:'room-twin',count:8,area:28},{floor:'standard',type:'room-double',count:4,area:24.5},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-compact-mix',title:'コンパクトホテル基準階（トリプル・ファミリー混在）',level:'標準',brief:'トリプル・ファミリー・セミダブルを混在させ、コンパクトな廊下計画でまとめる。',grid:{rows:3,cols:6,rowSpan:6,colSpan:8},requirements:[
  {floor:'standard',type:'room-triple',count:6,area:31.5},{floor:'standard',type:'room-family',count:4,area:38.5},{floor:'standard',type:'room-semidouble',count:4,area:21},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-boutique-standard',title:'ブティックホテル基準階（標準客室主体）',level:'標準',brief:'ダブルとツインを主体に、コンパクトなブティックホテルの基準階をまとめる。',grid:{rows:3,cols:4,rowSpan:8,colSpan:6},requirements:[
  {floor:'standard',type:'room-double',count:6,area:24.5,note:'2人用'},{floor:'standard',type:'room-twin',count:6,area:28,note:'2人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-airport-transit',title:'空港隣接トランジットホテル基準階（シングル特化）',level:'初級',brief:'短時間滞在向けにシングルのみで構成し、単純明快な廊下計画とする。',grid:{rows:3,cols:4,rowSpan:9,colSpan:6},requirements:[
  {floor:'standard',type:'room-single',count:20,area:17.5,note:'1人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-longstay-suite',title:'ロングステイ型基準階（スイート中心）',level:'上級',brief:'ジュニアスイートとスイートを中心に、長期滞在者向けのゆとりある基準階を計画する。',grid:{rows:3,cols:5,rowSpan:6,colSpan:9},requirements:[
  {floor:'standard',type:'room-junior-suite',count:4,area:45.5,note:'2人用'},{floor:'standard',type:'room-suite',count:3,area:66.5,note:'2～4人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-wellness-twin',title:'ウェルネスリゾート基準階（ツイン中心）',level:'標準',brief:'ツイン・デラックスツイン・身障者対応を組み合わせ、ゆとりある動線を確保する。',grid:{rows:3,cols:5,rowSpan:6,colSpan:7},requirements:[
  {floor:'standard',type:'room-twin',count:6,area:28,note:'2人用'},{floor:'standard',type:'room-deluxe-twin',count:3,area:35,note:'2人用'},{floor:'standard',type:'room-accessible',count:2,area:35,note:'身障者・車いす対応'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-conference-double',title:'コンベンションホテル基準階（ダブル中心）',level:'初級',brief:'ダブルとセミダブルを中心に、宴会・会議利用者向けの基準階をまとめる。',grid:{rows:3,cols:5,rowSpan:7,colSpan:6},requirements:[
  {floor:'standard',type:'room-double',count:8,area:24.5,note:'2人用'},{floor:'standard',type:'room-semidouble',count:6,area:21,note:'1～2人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-heritage-mixed',title:'歴史的建造物改修型基準階（複合客室）',level:'上級',brief:'既存建物の改修を想定し、シングル・ダブル・ジュニアスイートを混在させた不整形な動線を検討する。',grid:{rows:3,cols:4,rowSpan:7,colSpan:7},notch:{corner:'nw',w:6,h:10},requirements:[
  {floor:'standard',type:'room-single',count:6,area:17.5,note:'1人用'},{floor:'standard',type:'room-double',count:4,area:24.5,note:'2人用'},{floor:'standard',type:'room-junior-suite',count:2,area:45.5,note:'2人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-seaside-family',title:'シーサイドリゾート基準階（ファミリー特化）',level:'標準',brief:'ファミリー・ファミリー大を中心に、海側客室の眺望と動線を両立させる。',grid:{rows:3,cols:4,rowSpan:8,colSpan:7},requirements:[
  {floor:'standard',type:'room-family',count:5,area:38.5,note:'3～4人用'},{floor:'standard',type:'room-family-large',count:3,area:49,note:'4～5人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-capsule-hybrid',title:'次世代型基準階（コンパクト客室）',level:'初級',brief:'シングル・セミダブル・身障者対応の小型客室を組み合わせ、密度の高い基準階を計画する。',grid:{rows:3,cols:4,rowSpan:7,colSpan:8},requirements:[
  {floor:'standard',type:'room-single',count:10,area:17.5,note:'1人用'},{floor:'standard',type:'room-semidouble',count:4,area:21,note:'1～2人用'},{floor:'standard',type:'room-accessible',count:2,area:35,note:'身障者・車いす対応'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-executive-floor',title:'エグゼクティブフロア基準階（上級客室）',level:'上級',brief:'デラックスツイン・ジュニアスイート・スイートのみで構成する高グレードフロアを計画する。',grid:{rows:3,cols:5,rowSpan:6,colSpan:8},requirements:[
  {floor:'standard',type:'room-deluxe-twin',count:3,area:35,note:'2人用'},{floor:'standard',type:'room-junior-suite',count:3,area:45.5,note:'2人用'},{floor:'standard',type:'room-suite',count:2,area:66.5,note:'2～4人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-family-resort-L',title:'Lリゾートホテル基準階（ファミリー棟＋スタンダード棟）',level:'上級',brief:'ファミリー棟とツイン棟をL字に配置し、二方向避難と複合動線を検討する。',grid:{rows:3,cols:5,rowSpan:8,colSpan:6},notch:{corner:'ne',w:6,h:12},requirements:[
  {floor:'standard',type:'room-family',count:5,area:38.5,note:'3～4人用'},{floor:'standard',type:'room-twin',count:6,area:28,note:'2人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-citycenter-compact',title:'都心コンパクトホテル基準階',level:'初級',brief:'シングル・セミダブルを中心に、狭小敷地に対応したコンパクトな基準階をまとめる。',grid:{rows:3,cols:4,rowSpan:9,colSpan:6},requirements:[
  {floor:'standard',type:'room-single',count:10,area:17.5,note:'1人用'},{floor:'standard',type:'room-semidouble',count:6,area:21,note:'1～2人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-spa-retreat',title:'スパリトリート型基準階',level:'上級',brief:'デラックスツイン・身障者対応・ジュニアスイートを組み合わせ、不整形な平面での動線を検討する。',grid:{rows:3,cols:4,rowSpan:6,colSpan:9},notch:{corner:'sw',w:7,h:12},requirements:[
  {floor:'standard',type:'room-deluxe-twin',count:3,area:35,note:'2人用'},{floor:'standard',type:'room-accessible',count:2,area:35,note:'身障者・車いす対応'},{floor:'standard',type:'room-junior-suite',count:2,area:45.5,note:'2人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-business-L',title:'ビジネスホテルL型基準階',level:'標準',brief:'シングルとダブルをL字型の基準階に配置し、二方向避難経路を確保する。',grid:{rows:3,cols:5,rowSpan:6,colSpan:7},notch:{corner:'se',w:6,h:12},requirements:[
  {floor:'standard',type:'room-single',count:10,area:17.5,note:'1人用'},{floor:'standard',type:'room-double',count:4,area:24.5,note:'2人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-grand-suite-wing',title:'グランドスイート棟L型基準階',level:'上級',brief:'スイートとジュニアスイートのみをL字棟に配置する、最上級グレードの基準階を計画する。',grid:{rows:3,cols:6,rowSpan:7,colSpan:6},notch:{corner:'nw',w:7,h:14},requirements:[
  {floor:'standard',type:'room-suite',count:3,area:66.5,note:'2～4人用'},{floor:'standard',type:'room-junior-suite',count:3,area:45.5,note:'2人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-family-standard-mix',title:'ファミリー・スタンダード混在型基準階',level:'標準',brief:'ファミリー・ダブル・ツインを組み合わせ、多様な宿泊人数に対応する基準階をまとめる。',grid:{rows:3,cols:4,rowSpan:7,colSpan:7},requirements:[
  {floor:'standard',type:'room-family',count:4,area:38.5,note:'3～4人用'},{floor:'standard',type:'room-double',count:4,area:24.5,note:'2人用'},{floor:'standard',type:'room-twin',count:4,area:28,note:'2人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-accessible-focus',title:'バリアフリー重点型基準階',level:'標準',brief:'身障者・車いす対応客室を主体に、シングル・ダブルを組み合わせて計画する。',grid:{rows:3,cols:4,rowSpan:8,colSpan:7},requirements:[
  {floor:'standard',type:'room-accessible',count:6,area:35,note:'身障者・車いす対応'},{floor:'standard',type:'room-single',count:4,area:17.5,note:'1人用'},{floor:'standard',type:'room-double',count:4,area:24.5,note:'2人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-corner-lot-L',title:'角地対応L型基準階',level:'標準',brief:'角地の斜線制限を想定し、ツイン・トリプルをL字型の基準階に配置する。',grid:{rows:3,cols:4,rowSpan:7,colSpan:8},notch:{corner:'ne',w:7,h:12},requirements:[
  {floor:'standard',type:'room-twin',count:6,area:28,note:'2人用'},{floor:'standard',type:'room-triple',count:4,area:31.5,note:'3人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-highrise-standard',title:'超高層ホテル基準階（標準客室）',level:'標準',brief:'ダブル・ツイン・トリプルを組み合わせ、高層階特有の避難計画を重視する。',grid:{rows:3,cols:5,rowSpan:6,colSpan:8},requirements:[
  {floor:'standard',type:'room-double',count:5,area:24.5,note:'2人用'},{floor:'standard',type:'room-twin',count:5,area:28,note:'2人用'},{floor:'standard',type:'room-triple',count:3,area:31.5,note:'3人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-resort-suite-wing',title:'リゾートスイート棟L型基準階',level:'上級',brief:'ジュニアスイートとデラックスツインをL字棟に配置し、眺望と避難経路を両立させる。',grid:{rows:3,cols:4,rowSpan:8,colSpan:6},notch:{corner:'sw',w:6,h:10},requirements:[
  {floor:'standard',type:'room-junior-suite',count:3,area:45.5,note:'2人用'},{floor:'standard',type:'room-deluxe-twin',count:4,area:35,note:'2人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-value-single',title:'バリューホテル基準階（シングル大量配置）',level:'初級',brief:'シングル・セミダブルを大量配置し、効率重視の基準階をまとめる。',grid:{rows:3,cols:5,rowSpan:9,colSpan:6},requirements:[
  {floor:'standard',type:'room-single',count:18,area:17.5,note:'1人用'},{floor:'standard',type:'room-semidouble',count:4,area:21,note:'1～2人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-twin-heavy',title:'ツイン特化型基準階',level:'標準',brief:'ツインのみで構成する、シンプルなシティホテルの基準階を計画する。',grid:{rows:3,cols:5,rowSpan:6,colSpan:9},requirements:[
  {floor:'standard',type:'room-twin',count:16,area:28,note:'2人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-mixed-scale-L',title:'複合規模L型基準階',level:'上級',brief:'シングル・ファミリー・スイートという規模の異なる客室をL字型の基準階に混在させる。',grid:{rows:3,cols:6,rowSpan:6,colSpan:7},notch:{corner:'se',w:9,h:12},requirements:[
  {floor:'standard',type:'room-single',count:6,area:17.5,note:'1人用'},{floor:'standard',type:'room-family',count:3,area:38.5,note:'3～4人用'},{floor:'standard',type:'room-suite',count:2,area:66.5,note:'2～4人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-north-wing-L',title:'北棟L型基準階（トリプル中心）',level:'標準',brief:'トリプルとファミリー大を中心に、北側に張り出したL字棟を計画する。',grid:{rows:3,cols:5,rowSpan:7,colSpan:6},notch:{corner:'nw',w:6,h:12},requirements:[
  {floor:'standard',type:'room-triple',count:5,area:31.5,note:'3人用'},{floor:'standard',type:'room-family-large',count:3,area:49,note:'4～5人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]},
 {id:'hotel-panorama-suite',title:'パノラマスイート基準階',level:'上級',brief:'スイートとデラックスツインのみで構成する眺望重視の基準階を計画する。',grid:{rows:3,cols:4,rowSpan:7,colSpan:7},requirements:[
  {floor:'standard',type:'room-suite',count:3,area:66.5,note:'2～4人用'},{floor:'standard',type:'room-deluxe-twin',count:4,area:35,note:'2人用'},{floor:'standard',type:'linen',count:1,area:10.5},{floor:'standard',type:'air-cond',count:1,area:6},{floor:'standard',type:'stairs-access',count:1,area:24.5,note:'利用者用'},{floor:'standard',type:'stairs-code',count:1,area:15,note:'管理用'},{floor:'standard',type:'ev-small',count:1,area:4,note:'管理用'},{floor:'standard',type:'ev-large',count:2,area:8.75,note:'利用者用'}
 ]}
];
const guestRoomTypeIds=['room-single','room-semidouble','room-double','room-twin','room-triple','room-deluxe-twin','room-accessible','room-family','room-family-large','room-junior-suite','room-suite'];

const learningFloorNames={standard:'基準階'};
let activeChallenge=loadActiveChallenge();

function cloneLearning(value){return JSON.parse(JSON.stringify(value))}
// 課題で定義されたスパン・欠き込みはそのまま使う（スパン列は描画用に展開するだけ）
function normalizeChallenge(ch){const g=ch.grid;
 g.colSpans=Array(g.cols).fill(g.colSpan);
 g.rowSpans=Array(g.rows).fill(g.rowSpan);
 return ch}
function loadActiveChallenge(){try{const saved=JSON.parse(localStorage.getItem('esquisse_active_problem'));if(saved&&saved.requirements)return normalizeChallenge(saved)}catch(e){}return normalizeChallenge(cloneLearning(learningChallenges[0]))}
function saveActiveChallenge(){localStorage.setItem('esquisse_active_problem',JSON.stringify(activeChallenge))}
const hotelGridSpans=[[6,7],[7,6],[7,7],[8,7],[7,8],[6,8],[8,6],[9,6],[6,9]];
const GROSS_AREA_FACTOR=1.65;
function gridForRequirements(requirements){const netArea=requirements.reduce((n,r)=>n+r.area*r.count,0),targetGross=netArea*GROSS_AREA_FACTOR,[rowSpan,colSpan]=hotelGridSpans[Math.floor(Math.random()*hotelGridSpans.length)],rows=3,cols=Math.max(4,Math.round(targetGross/(rows*rowSpan*colSpan)));return{rows,cols,rowSpan,colSpan}}
function generateLearningChallenge(){const choices=learningChallenges.filter(c=>c.id!==activeChallenge.id),base=cloneLearning(choices[Math.floor(Math.random()*choices.length)]||learningChallenges[0]),variation=Math.floor(Math.random()*900)+100;base.id=`${base.id}-${Date.now()}`;base.title=`${base.title} 自動課題${variation}`;delete base.notch;const adjustable=base.requirements.filter(r=>guestRoomTypeIds.includes(r.type));if(adjustable.length){const req=adjustable[Math.floor(Math.random()*adjustable.length)];req.count+=2;req.note=(req.note?req.note+'・':'')+'自動生成による追加条件'}base.grid=gridForRequirements(base.requirements);return normalizeChallenge(base)}
function learningTypeName(id){return types.find(t=>t.id===id)?.name||id}
function learningCenter(p){return{x:p.x+p.w/2,y:p.y+p.h/2}}
function learningDistance(a,b){const ac=learningCenter(a),bc=learningCenter(b);return Math.abs(ac.x-bc.x)+Math.abs(ac.y-bc.y)}
function placedFor(floor,type){return state.pieces.filter(p=>p.floor===floor&&p.type===type)}
function reqStatus(req){const found=placedFor(req.floor,req.type),valid=found.filter(p=>p.w*p.h+0.01>=req.area);return{found,valid,ok:valid.length>=req.count,area:found.reduce((n,p)=>n+p.w*p.h,0)}}
const CORRIDOR_CELL=0.5,MIN_CORRIDOR_WIDTH=2.5;
function buildCorridorAnalysis(floor){
 const totalW=gridW(),totalH=gridH(),cols=Math.round(totalW/CORRIDOR_CELL),rows=Math.round(totalH/CORRIDOR_CELL),n=notchRect(),pieces=state.pieces.filter(p=>p.floor===floor&&!isDraftingType(p.type)),free=Array.from({length:rows},()=>new Array(cols).fill(true));
 for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const cx=(c+.5)*CORRIDOR_CELL,cy=(r+.5)*CORRIDOR_CELL;if(n&&cx>n.x&&cx<n.x+n.w&&cy>n.y&&cy<n.y+n.h){free[r][c]=false;continue}for(const p of pieces)if(cx>p.x&&cx<p.x+p.w&&cy>p.y&&cy<p.y+p.h){free[r][c]=false;break}}
 const left=Array.from({length:rows},()=>new Array(cols).fill(0)),right=Array.from({length:rows},()=>new Array(cols).fill(0)),up=Array.from({length:rows},()=>new Array(cols).fill(0)),down=Array.from({length:rows},()=>new Array(cols).fill(0));
 for(let r=0;r<rows;r++){for(let c=0;c<cols;c++)left[r][c]=free[r][c]?(c>0&&free[r][c-1]?left[r][c-1]+1:1):0;for(let c=cols-1;c>=0;c--)right[r][c]=free[r][c]?(c<cols-1&&free[r][c+1]?right[r][c+1]+1:1):0}
 for(let c=0;c<cols;c++){for(let r=0;r<rows;r++)up[r][c]=free[r][c]?(r>0&&free[r-1][c]?up[r-1][c]+1:1):0;for(let r=rows-1;r>=0;r--)down[r][c]=free[r][c]?(r<rows-1&&free[r+1][c]?down[r+1][c]+1:1):0}
 const valid=Array.from({length:rows},()=>new Array(cols).fill(false));let narrowCount=0;
 for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){if(!free[r][c])continue;const hSpan=(left[r][c]+right[r][c]-1)*CORRIDOR_CELL,vSpan=(up[r][c]+down[r][c]-1)*CORRIDOR_CELL,w=Math.min(hSpan,vSpan);if(w>=MIN_CORRIDOR_WIDTH)valid[r][c]=true;else narrowCount++}
 return{rows,cols,valid,narrowCount}
}
function touchingValidCells(analysis,p){const{valid,rows,cols}=analysis,cells=[],x0=Math.round(p.x/CORRIDOR_CELL),y0=Math.round(p.y/CORRIDOR_CELL),x1=Math.round((p.x+p.w)/CORRIDOR_CELL),y1=Math.round((p.y+p.h)/CORRIDOR_CELL);for(let c=Math.max(0,x0);c<Math.min(cols,x1);c++){if(y0-1>=0&&valid[y0-1][c])cells.push(y0-1+','+c);if(y1<rows&&valid[y1][c])cells.push(y1+','+c)}for(let r=Math.max(0,y0);r<Math.min(rows,y1);r++){if(x0-1>=0&&valid[r][x0-1])cells.push(r+','+(x0-1));if(x1<cols&&valid[r][x1])cells.push(r+','+x1)}return cells}
function corridorBfsDistance(analysis,startKeys,targetSet){const{valid,rows,cols}=analysis;if(!startKeys.length)return Infinity;const dist=new Map(),queue=[];for(const key of startKeys)if(!dist.has(key)){dist.set(key,0);queue.push(key)}let qi=0;while(qi<queue.length){const key=queue[qi++],d=dist.get(key);if(targetSet.has(key))return d*CORRIDOR_CELL;const[r,c]=key.split(',').map(Number);for(const[nr,nc]of[[r-1,c],[r+1,c],[r,c-1],[r,c+1]]){if(nr<0||nr>=rows||nc<0||nc>=cols||!valid[nr][nc])continue;const nk=nr+','+nc;if(!dist.has(nk)){dist.set(nk,d+1);queue.push(nk)}}}return Infinity}
function gradeLearningPlan(){
 const feedback=[],categories={program:45,circulation:30,evacuation:25};
 const failedReq=activeChallenge.requirements.filter(r=>!reqStatus(r).ok);categories.program=Math.max(0,45-failedReq.length*4);failedReq.forEach(r=>feedback.push({level:'bad',text:`${learningFloorNames[r.floor]}：${learningTypeName(r.type)} ${r.count}室・各${r.area}㎡以上が不足しています。`}));if(!failedReq.length)feedback.push({level:'good',text:'要求室の個数と最低面積を満たしています。'});
 let noCorridor=0,routeFailures=0,maxRoute=0,stairProblem=0,narrowTotal=0;
 for(const [floor] of floorDefs){
  const analysis=buildCorridorAnalysis(floor);narrowTotal+=analysis.narrowCount;
  const pieces=state.pieces.filter(p=>p.floor===floor&&!isDraftingType(p.type)),rooms=pieces.filter(p=>types.find(t=>t.id===p.type)?.unit),stairs=pieces.filter(p=>p.type.startsWith('stairs'));
  const roomTouch=rooms.map(room=>({room,cells:touchingValidCells(analysis,room)}));
  roomTouch.forEach(rt=>{if(!rt.cells.length)noCorridor++});
  if(stairs.length<2){stairProblem++;feedback.push({level:'bad',text:`${learningFloorNames[floor]}：利用者階段と管理用階段の2か所が必要です。`});continue}
  const sep=learningDistance(stairs[0],stairs[1]);if(sep<14){stairProblem++;feedback.push({level:'warn',text:`${learningFloorNames[floor]}：2つの階段が近すぎます（中心間約${sep.toFixed(1)}m）。`})}
  const stairTargets=stairs.map(s=>new Set(touchingValidCells(analysis,s)));
  for(const rt of roomTouch){if(!rt.cells.length)continue;const routes=stairTargets.map(target=>corridorBfsDistance(analysis,rt.cells,target));if(routes.filter(Number.isFinite).length<2)routeFailures++;const best=Math.min(...routes);if(Number.isFinite(best))maxRoute=Math.max(maxRoute,best)}
 }
 if(noCorridor){categories.circulation=Math.max(0,30-Math.min(30,noCorridor*3));feedback.push({level:'bad',text:`廊下（空白部分）に接していない要求室が${noCorridor}室あります。部屋の間に幅2.5mを超える空間を確保してください。`})}else feedback.push({level:'good',text:'各要求室は廊下（空白部分）に接続しています。'});
 if(narrowTotal){categories.circulation=0;feedback.push({level:'bad',text:'廊下幅が2.5m以下になっている箇所があります。この案は成立しません（アウト）。部屋の間隔を2.5mより広く空けてください。'})}
 if(routeFailures||stairProblem){categories.evacuation=Math.max(0,25-routeFailures*3-stairProblem*5);if(routeFailures)feedback.push({level:'bad',text:`2つの階段へ到達できない室が${routeFailures}室あります。廊下（空白部分）を両階段まで連続させてください。`})}else feedback.push({level:'good',text:`二方向避難経路を確認しました。推定最大歩行距離は約${maxRoute.toFixed(1)}mです。`});
 if(maxRoute>60){categories.evacuation=Math.max(0,categories.evacuation-6);feedback.push({level:'warn',text:`推定歩行距離${maxRoute.toFixed(1)}mは60mを超えています。階段位置を再検討してください。`})}
 const total=Object.values(categories).reduce((a,b)=>a+b,0),gross={};floorDefs.forEach(([f])=>gross[f]=state.pieces.filter(p=>p.floor===f&&!isDraftingType(p.type)).reduce((n,p)=>n+p.w*p.h,0));return{total,categories,feedback,maxRoute,gross,failedReq,at:new Date().toLocaleString('ja-JP')}
}

function updateStudyStrip(){const result=gradeLearningPlan(),done=activeChallenge.requirements.length-result.failedReq.length;$('#active-problem-title').textContent=`${activeChallenge.title}［${activeChallenge.level}］`;$('#active-problem-brief').textContent=activeChallenge.brief;$('#study-progress').innerHTML=`要求室 <strong>${done}/${activeChallenge.requirements.length}</strong>　暫定 <strong>${result.total}点</strong>`;$('#study-requirements').innerHTML=activeChallenge.requirements.map(r=>{const status=reqStatus(r);return `<span class="req-chip ${status.ok?'ok':'ng'}">${learningTypeName(r.type)} ${status.valid.length}/${r.count}</span>`}).join('')}
function openLearningDrawer(title,html){$('#drawer-title').textContent=title;$('#drawer-content').innerHTML=html;$('#learning-drawer').hidden=false;$('#drawer-backdrop').hidden=false}
function closeLearningDrawer(){$('#learning-drawer').hidden=true;$('#drawer-backdrop').hidden=true}
function renderProblemDrawer(){const rows=activeChallenge.requirements.map((r,i)=>{const status=reqStatus(r);return`<tr><td>${learningFloorNames[r.floor]}</td><td>${learningTypeName(r.type)}${r.note?`<small><br>${r.note}</small>`:''}</td><td><input data-req-count="${i}" type="number" min="1" value="${r.count}"></td><td><input data-req-area="${i}" type="number" min="1" step="0.5" value="${r.area}"></td><td class="${status.ok?'ok':'ng'}">${status.ok?'OK':`${status.valid.length}/${r.count}`}</td></tr>`}).join('');openLearningDrawer('課題条件',`<div class="problem-lead"><b>${activeChallenge.title}</b><br>${activeChallenge.brief}</div><div class="condition-grid"><span>難易度：${activeChallenge.level}</span><span>グリッド：${activeChallenge.grid.cols}×${activeChallenge.grid.rows}</span><span>スパン：${activeChallenge.grid.colSpan}m×${activeChallenge.grid.rowSpan}m</span><span>形状：${activeChallenge.notch?`L型（${cornerNames[activeChallenge.notch.corner]}${activeChallenge.notch.w}×${activeChallenge.notch.h}mを除く）`:'矩形'}</span></div><div class="drawer-actions"><button id="new-problem">別の課題</button><button id="apply-problem" class="primary-action">この課題を開始</button></div><p class="hint">個数と最低面積は、この課題用に編集できます。</p><table class="requirement-table"><thead><tr><th>階</th><th>要求室</th><th>数</th><th>㎡/室</th><th>判定</th></tr></thead><tbody>${rows}</tbody></table>`);document.querySelectorAll('[data-req-count]').forEach(input=>input.onchange=e=>{activeChallenge.requirements[+e.target.dataset.reqCount].count=Math.max(1,+e.target.value);saveActiveChallenge();renderProblemDrawer()});document.querySelectorAll('[data-req-area]').forEach(input=>input.onchange=e=>{activeChallenge.requirements[+e.target.dataset.reqArea].area=Math.max(1,Math.round(+e.target.value*2)/2);saveActiveChallenge();renderProblemDrawer()});$('#new-problem').onclick=()=>{const index=learningChallenges.findIndex(c=>c.id===activeChallenge.id),next=learningChallenges[(index+1)%learningChallenges.length];activeChallenge=normalizeChallenge(cloneLearning(next));saveActiveChallenge();renderProblemDrawer();updateStudyStrip()};$('#apply-problem').onclick=()=>{if(state.pieces.length&&!confirm('現在の配置を消して、この課題を開始しますか？'))return;snap();state={version:5,...cloneLearning(activeChallenge.grid),notch:activeChallenge.notch?cloneLearning(activeChallenge.notch):null,pieces:[]};selectedPiece=null;persist();syncRoomCounts();renderRooms();renderFloors();renderSelection();closeLearningDrawer();toast('新しい課題を開始しました')}}
function renderGradeDrawer(result=gradeLearningPlan()){const categoryNames={program:'要求室・面積',circulation:'廊下・接続',evacuation:'二方向避難'},maximums={program:45,circulation:30,evacuation:25},bars=Object.entries(result.categories).map(([k,v])=>`<div class="score-category"><div><span>${categoryNames[k]}</span><b>${v}/${maximums[k]}</b></div><div class="score-bar"><i style="width:${v/maximums[k]*100}%"></i></div></div>`).join(''),feedback=result.feedback.map(x=>`<div class="feedback ${x.level}">${x.text}</div>`).join(''),areas=Object.entries(result.gross).map(([f,a])=>`${learningFloorNames[f]} ${a.toFixed(1)}㎡`).join(' ／ ');openLearningDrawer('自動採点',`<div class="score-hero"><div class="score-ring" style="--score:${result.total}"><strong>${result.total}</strong></div><div><h3>${result.total>=80?'成立性の高い案です':result.total>=60?'改善すれば成立します':'骨格から再検討してください'}</h3><p>面積・接続・避難経路を、現在の配置から自動判定しました。</p></div></div>${bars}<p class="hint">床面積集計：${areas}</p><div class="feedback-list">${feedback}</div>`)}
function learningSchemes(){try{return JSON.parse(localStorage.getItem('esquisse_schemes')||'[]')}catch(e){return[]}}
function saveLearningScheme(){const list=learningSchemes(),result=gradeLearningPlan(),name=`案${list.length+1}`;list.push({id:crypto.randomUUID(),name,problem:activeChallenge.title,state:cloneLearning(state),result,created:new Date().toLocaleString('ja-JP')});localStorage.setItem('esquisse_schemes',JSON.stringify(list.slice(-8)));toast(`${name}を保存しました`);renderCompareDrawer()}
function renderCompareDrawer(){const list=learningSchemes();if(!list.length)return openLearningDrawer('案を比較','<div class="empty-state">保存した案がありません。<br>「案を保存」から現在の配置を保存してください。</div>');const cards=list.map((s,i)=>`<div class="scheme-card"><div class="scheme-card-head"><h3>${s.name} <small>${s.problem}</small></h3><strong>${s.result.total}点</strong></div><p>${s.created}<br>要求室 ${s.result.failedReq.length?'不足'+s.result.failedReq.length+'項目':'充足'}・最大歩行距離 ${s.result.maxRoute.toFixed(1)}m</p><button data-load-scheme="${i}">この案を開く</button> <button data-delete-scheme="${i}">削除</button></div>`).join(''),compare=list.slice(-3).map(s=>`<div class="compare-card"><b>${s.name}</b><strong>${s.result.total}</strong><span>面積${s.result.categories.program} / 動線${s.result.categories.circulation}<br>避難${s.result.categories.evacuation}</span></div>`).join('');openLearningDrawer('案を保存・比較',`<div class="compare-grid">${compare}</div><div class="drawer-actions"><button id="save-current-scheme" class="primary-action">現在案を保存</button></div>${cards}`);$('#save-current-scheme').onclick=saveLearningScheme;document.querySelectorAll('[data-load-scheme]').forEach(b=>b.onclick=e=>{const saved=learningSchemes()[+e.target.dataset.loadScheme];if(!saved||!confirm(`${saved.name}を開きますか？ 現在の未保存状態は失われます。`))return;snap();state=cloneLearning(saved.state);selectedPiece=null;persist();renderRooms();renderFloors();renderSelection();closeLearningDrawer();toast(`${saved.name}を開きました`)});document.querySelectorAll('[data-delete-scheme]').forEach(b=>b.onclick=e=>{const items=learningSchemes();items.splice(+e.target.dataset.deleteScheme,1);localStorage.setItem('esquisse_schemes',JSON.stringify(items));renderCompareDrawer()})}

const renderProblemDrawerLearningBase=renderProblemDrawer;renderProblemDrawer=function(){renderProblemDrawerLearningBase();const button=$('#new-problem');button.textContent='課題を自動生成';button.onclick=()=>{activeChallenge=generateLearningChallenge();saveActiveChallenge();renderProblemDrawer();updateStudyStrip()}};
const gradeLearningPlanBase=gradeLearningPlan;gradeLearningPlan=function(){const result=gradeLearningPlanBase(),totalW=gridW(),totalH=gridH(),interior=state.pieces.filter(p=>!isDraftingType(p.type)),outside=interior.filter(p=>p.x<0||p.y<0||p.x+p.w>totalW+.01||p.y+p.h>totalH+.01),overlaps=[];for(const [floor] of floorDefs){const list=interior.filter(p=>p.floor===floor);for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j];if(a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y)overlaps.push([a,b])}}if(outside.length||overlaps.length){result.categories.program=Math.max(0,result.categories.program-8);result.feedback.push({level:'bad',text:`建築範囲外の要素${outside.length}件、重なり${overlaps.length}件を検出しました。`})}result.total=Object.values(result.categories).reduce((a,b)=>a+b,0);return result};
const learningRenderFloorsBase=renderFloors;renderFloors=function(){learningRenderFloorsBase();updateStudyStrip()};
function syncRoomCounts(){types.forEach(t=>{const req=activeChallenge.requirements.find(r=>r.type===t.id);t.count=req?req.count:0});const current=types.find(t=>t.id===selectedType);if(!current||!(current.count>0||alwaysVisibleTypeIds.includes(current.id))){const first=activeChallenge.requirements.find(r=>guestRoomTypeIds.includes(r.type));if(first){selectedType=first.type;selectedRotated=false}}}
$('#open-problem').onclick=renderProblemDrawer;$('#grade-plan').onclick=()=>renderGradeDrawer();$('#quick-grade').onclick=()=>renderGradeDrawer();$('#save-scheme').onclick=saveLearningScheme;$('#compare-schemes').onclick=renderCompareDrawer;$('#close-drawer').onclick=closeLearningDrawer;$('#drawer-backdrop').onclick=closeLearningDrawer;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLearningDrawer()});
syncRoomCounts();renderRooms();updateSummary();updateStudyStrip();
