const multiSelectedIds=new Set();
let multiClipboard=null,multiPasteTarget={floor:'standard',x:0,y:0};
document.addEventListener('pointerdown',event=>{const hit=event.target.closest('.piece'),draggingSelection=hit&&multiSelectedIds.has(hit.dataset.pid)&&multiLogicalCount()>=2;if(event.button===0&&!(event.ctrlKey||event.metaKey)&&event.target.closest('.grid')&&!draggingSelection)multiSelectedIds.clear()},true);
document.addEventListener('pointerdown',event=>{const grid=event.target.closest('.grid');if(grid){const rect=grid.getBoundingClientRect();multiPasteTarget={floor:grid.dataset.grid,x:Math.round((event.clientX-rect.left)/rect.width*gridW()*2)/2,y:Math.round((event.clientY-rect.top)/rect.height*gridH()*2)/2}}const pieceElement=event.target.closest('.piece');if(!(event.ctrlKey||event.metaKey)||event.button!==0||!pieceElement)return;event.preventDefault();event.stopImmediatePropagation();const piece=state.pieces.find(p=>p.id===pieceElement.dataset.pid);if(!piece)return;const ids=linked(piece).map(p=>p.id),remove=ids.every(id=>multiSelectedIds.has(id));ids.forEach(id=>remove?multiSelectedIds.delete(id):multiSelectedIds.add(id));selectedPiece=remove?(multiSelectedIds.values().next().value||null):piece.id;renderFloors();renderMultiSelectionPanel();toast(`${multiLogicalCount()}件を複数選択中`)},true);
document.addEventListener('contextmenu',event=>{const grid=event.target.closest('.grid');if(!grid)return;const hit=event.target.closest('.piece'),hitSelected=hit&&multiSelectedIds.has(hit.dataset.pid),multiple=multiLogicalCount()>=2;if(hit&&!(hitSelected&&multiple))return;if(!hit&&(copiedPiece||!multiClipboard))return;event.preventDefault();event.stopImmediatePropagation();const rect=grid.getBoundingClientRect(),x=Math.round((event.clientX-rect.left)/rect.width*gridW()*2)/2,y=Math.round((event.clientY-rect.top)/rect.height*gridH()*2)/2;multiPasteTarget={floor:grid.dataset.grid,x,y};showMultiContextMenu(event.clientX,event.clientY,hitSelected)},true);
function isMovableRoom(type){return!isDraftingType(type)}

document.addEventListener('pointerdown',event=>{const pieceElement=event.target.closest('.piece');if(event.button!==0||!pieceElement||event.target.closest('.resize-handle'))return;const piece=state.pieces.find(p=>p.id===pieceElement.dataset.pid),groupDrag=piece&&multiSelectedIds.has(piece.id)&&multiLogicalCount()>=2;if(!piece||(!isMovableRoom(piece.type)&&!groupDrag))return;const grid=pieceElement.closest('.grid');if(!grid)return;event.preventDefault();event.stopImmediatePropagation();selectedPiece=piece.id;document.querySelectorAll('.piece.selected').forEach(el=>el.classList.remove('selected'));pieceElement.classList.add('selected');renderSelection();const rect=grid.getBoundingClientRect(),totalW=gridW(),totalH=gridH(),parts=groupDrag?multiPieces():linked(piece),ids=parts.map(p=>p.id),origins=parts.map(p=>({p,x:p.x,y:p.y})),startClientX=event.clientX,startClientY=event.clientY;snap();let moved=false;const move=ev=>{const dx=Math.round((ev.clientX-startClientX)/rect.width*totalW*2)/2,dy=Math.round((ev.clientY-startClientY)/rect.height*totalH*2)/2;const targets=origins.map(origin=>({origin,x:origin.x+dx,y:origin.y+dy}));if(targets.length===1){const t=targets[0],p=t.origin.p;if(!isDraftingType(p.type)){const fit=(x,y)=>canPlace(p.floor,x,y,p.w,p.h,ids,p.type);const st=snapToStructure(t.x,t.y,p.w,p.h);if(fit(st.x,st.y)){t.x=st.x;t.y=st.y}const snapped=snapToNeighbors(p.floor,t.x,t.y,p.w,p.h,ids);if(fit(snapped.x,snapped.y)){t.x=snapped.x;t.y=snapped.y}}}if(targets.every(t=>canPlace(t.origin.p.floor,t.x,t.y,t.origin.p.w,t.origin.p.h,ids,t.origin.p.type))){targets.forEach(t=>{t.origin.p.x=t.x;t.origin.p.y=t.y});moved=true;renderFloors()}};const up=()=>{persist();if(!moved)renderFloors();renderSelection();if(groupDrag)toast(`${multiLogicalCount()}件を一緒に移動しました`);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)},true);

function multiPieces(){return state.pieces.filter(p=>multiSelectedIds.has(p.id))}
function multiLogicalCount(){return new Set(multiPieces().map(p=>p.groupId||p.id)).size}
function markMultiSelected(){multiSelectedIds.forEach(id=>document.querySelector(`[data-pid="${id}"]`)?.classList.add('multi-selected'))}
function renderMultiSelectionPanel(){if(multiSelectedIds.size<2)return;const box=$('#selection'),pieces=multiPieces(),names=[...new Set(pieces.map(p=>learningTypeName(p.type)))];box.className='multi-selection-card';box.innerHTML=`<b>複数選択：${multiLogicalCount()}件</b><small>${names.join('、')}<br>選択中の要素をドラッグすると、全体を一緒に移動できます。<br>Ctrl＋クリックで追加・解除できます。</small><button id="copy-multiple">選択をコピー</button><button id="delete-multiple">選択を削除</button>`;$('#copy-multiple').onclick=copyMultiSelection;$('#delete-multiple').onclick=deleteMultiSelection}
function copyMultiSelection(){const pieces=multiPieces();if(!pieces.length)return toast('コピーする要素を選択してください');const source=state.pieces.find(p=>p.id===selectedPiece)||pieces[0],sourceFloor=source.floor,sourceItems=pieces.filter(p=>p.floor===sourceFloor),reference=sourceItems.length?sourceItems:pieces,minX=Math.min(...reference.map(p=>p.x)),minY=Math.min(...reference.map(p=>p.y));multiClipboard={sourceFloor,minX,minY,items:pieces.map(p=>({...p,groupKey:p.groupId||null}))};copiedPiece=null;toast(`${multiLogicalCount()}件をコピーしました`)}
function deleteMultiSelection(){if(!multiSelectedIds.size)return;snap();const ids=new Set(multiSelectedIds);state.pieces=state.pieces.filter(p=>!ids.has(p.id));multiSelectedIds.clear();selectedPiece=null;persist();renderFloors();renderSelection();toast('複数選択した要素を削除しました')}
function multiProposalCollides(items){for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++){const a=items[i],b=items[j];if(a.floor===b.floor&&!isDraftingType(a.type)&&!isDraftingType(b.type)&&a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y)return true}return false}
function pasteMultiSelection(floor,x,y){if(!multiClipboard?.items.length)return toast('複数コピーした要素がありません');const dx=Math.round((x-multiClipboard.minX)*2)/2,dy=Math.round((y-multiClipboard.minY)*2)/2,groupMap=new Map(),items=multiClipboard.items.map(item=>{const core=!!item.groupKey;if(core&&!groupMap.has(item.groupKey))groupMap.set(item.groupKey,crypto.randomUUID());return{...item,id:crypto.randomUUID(),groupId:core?groupMap.get(item.groupKey):null,floor:core?item.floor:(item.floor===multiClipboard.sourceFloor?floor:item.floor),x:item.x+dx,y:item.y+dy}});if(multiProposalCollides(items)||!items.every(p=>canPlace(p.floor,p.x,p.y,p.w,p.h,[],p.type)))return toast('貼り付け先に空きがありません');snap();state.pieces.push(...items);multiSelectedIds.clear();items.forEach(p=>multiSelectedIds.add(p.id));selectedPiece=items.find(p=>p.floor===floor)?.id||items[0].id;persist();renderFloors();renderMultiSelectionPanel();toast(`${new Set(items.map(p=>p.groupId||p.id)).size}件を貼り付けました`)}
function showMultiContextMenu(clientX,clientY,hitSelected){const menu=$('#context-menu'),selected=multiLogicalCount(),copied=multiClipboard?new Set(multiClipboard.items.map(p=>p.groupKey||p.id)).size:0;menu.innerHTML=`${selected?`<span class="menu-heading">${selected}件を選択中</span><button data-multi="copy">選択をコピー</button><button class="danger" data-multi="delete">選択を削除</button>`:''}${copied?`<button data-multi="paste">ここへ${copied}件を貼り付け</button>`:''}${!selected&&!copied?'<span>複数選択してください</span>':''}`;menu.hidden=false;menu.style.left=clientX+'px';menu.style.top=clientY+'px';menu.onclick=e=>{const action=e.target.dataset.multi;if(action==='copy')copyMultiSelection();if(action==='delete')deleteMultiSelection();if(action==='paste')pasteMultiSelection(multiPasteTarget.floor,multiPasteTarget.x,multiPasteTarget.y);menu.hidden=true}}
document.addEventListener('keydown',event=>{if(event.target.matches('input,textarea,select'))return;const ctrl=event.ctrlKey||event.metaKey;if(ctrl&&event.key.toLowerCase()==='c'&&multiSelectedIds.size){event.preventDefault();copyMultiSelection()}if(ctrl&&event.key.toLowerCase()==='v'&&multiClipboard){event.preventDefault();pasteMultiSelection(multiPasteTarget.floor,multiPasteTarget.x,multiPasteTarget.y)}if((event.key==='Delete'||event.key==='Backspace')&&multiSelectedIds.size>1){event.preventDefault();deleteMultiSelection()}});
const multiRenderFloorsBase=renderFloors;renderFloors=function(){multiRenderFloorsBase();markMultiSelected()};
const multiRenderSelectionBase=renderSelection;renderSelection=function(){multiRenderSelectionBase();renderMultiSelectionPanel()};
markMultiSelected();
